### ISSUE TITLE
Requests after readyState goes to idle or complete

### ISSUE THREAD

**Issue by bernardeli** [kapouer/node-webkitgtk#21]
Hey there!

I'm having an issue with requests that are made after `webview.readyState` goes to `complete`, and async requests are not being fired off. 

That usually happens with javascript that creates more requests within itself.

Please have a look at the script below:

```
var Webkit = require('webkitgtk');

var url        = 'http://d3s84xo5cmutkt.cloudfront.net/renders/attachments/000/011/601/original/latest_just-map.html';
var portView   = { width: 567, height: 756 }; // Pixels
var requests   = 0;

var webview = Webkit();

webview.load(url, portView);

webview.on('request', function (request) {
  requests += 1;
  console.log('# Counter on request: ' + requests + ', state is: ' + webview.readyState);
  console.log('# URL: ' + request.uri);
});

webview.on('response', function (response) {
  requests -= 1;
  console.log('# Counter on response: ' + requests + ', state is: ' + webview.readyState);

  if (requests === 0) {
    console.log(webview.readyState);
    printPdf();
  }
});

webview.on('busy', function() {
  console.log("##### STILL BUSY!");
});

webview.on('console', function (level, message) {
  // console.log("\n## Console log: " + JSON.stringify(message) + "\n");
});

function printPdf() {
  console.log("Rendering PDF. State: " + webview.readyState);

  var filename  = 'renders/output.pdf';
  var paperSize = { paper: { width: 150, height: 200, unit: 'mm' } };

  webview.pdf(filename, paperSize, function(err) {
    if (err) {
      webview.destroy();
      console.log(err.toString());
    }

    console.log('Render done!');
    webview.destroy();
  });
}
```

It should only render when the requests counter reaches zero. However, one of the calls to openmaps performs other async calls to each of the map tiles. It's possible to see that with Chrome:
![chrome](https://s3.amazonaws.com/f.cl.ly/items/2r2U3A0p183z1G0O0L2Y/Image%202015-02-17%20at%2010.31.37%20am.png)

From what I understood after digging into `webkitgtk.js` file:

* It goes to `idle` and no more requests are performed, unless `loop.call(this, true)` is called again.
* I tried `debug: true` so that `priv.inspecting` is true, therefore this [code](https://github.com/kapouer/node-webkitgtk/blob/master/webkitgtk.js#L584-L589) would never get executed.
* I get the requests happening, and I can see it because the script listens to `webview.on('request')`.

The problem I see here is: I'm not able to count requests with the script either because the counter reaches zero before the next async request is made, therefore the pdf function being called when not all requests were actually loaded, or sometimes being called twice as the counter increments/decrements again, going to zero twice or more.

I'm not entirely sure either it is a bug on node-webkitgtk or I'm not treating that with my script in the right way. I'd appreciate if you could shed some light for me. 

If you need more clarification, please let me know.

Cheers

**Comment by kapouer** [comment]
At the bottom of the README there a short explanation about the gtk loop.
node-webkitgtk stops running it after 'load' event. To prevent this, listen for 'unload' event until destruction.
Also note that your code can be achieved by simply doing
`WebKit().load(url).wait('idle').pdf(filename, paperSize).destroy(function(err) { if (err) console.error(err);});` though you need latest version to actually get the latest callback being called.

**Comment by kapouer** [comment]
(version 1.17.1 being pushed)

**Comment by kapouer** [comment]
Note also that 'busy' event is something very special to deal with. Usually you just need to wait for the 'idle' event.

**Comment by bernardeli** [comment]
Awesome, thanks heaps for your help @kapouer. 

I've simplified it to the below:

```
var Webkit = require('webkitgtk');

var url        = 'http://d3s84xo5cmutkt.cloudfront.net/renders/attachments/000/011/601/original/latest_just-map.html';
var portView   = { width: 567, height: 756 }; // Pixels
var requests   = 0;
var filename  = 'renders/output.pdf';
var paperSize = { paper: { width: 150, height: 200, unit: 'mm' } };

var webview = Webkit();

webview.on('request', function (request) {
  requests += 1;
  console.log('# Counter on request: ' + requests + ', state is: ' + webview.readyState);
  console.log('# URL: ' + request.uri);
});

webview.on('response', function (response) {
  requests -= 1;
  console.log('# Counter on response: ' + requests + ', state is: ' + webview.readyState);
  console.log('# URL: ' + response.uri);
});

// webview.on('idle', function() { this.loop(true); });
webview.on('unload', function() { console.log('Unload being accessed'); });

webview.load(url, portView)
  .wait('idle')
  .pdf(filename, paperSize, function() { console.log("Rendering"); })
  .destroy(function(err) { if (err) console.error(err);});
```

README says:

> Use .on('idle', function() { this.loop(true); }) to restart the gtk loop if needed.

I'm trying to access the loop when it goes idle, however, `this` in the context is a webkit, and `loop` isn't  a webkit method.

If you remove comments from `webview.on('idle', function() { this.loop(true); });`, it raises `TypeError: Object #<WebKit> has no method 'loop'`.

Also, can you explain how listening to `unload` would keep the loop alive? There's a listener on my code, but it never fires off the call I'm afraid.

Cheers

**Comment by bernardeli** [comment]
So I ended up exposing `loop` function with the following:

```
WebKit.prototype.loop = function(arg) {
        loop.call(this, arg);
};
```

And it didn't actually solve my problem...

I did some debugging by deleting code so that I could get a better understanding overall. 

I found that what I am trying to solve is inside `stateTracker`, and something weird happens here. With this updated script https://gist.github.com/bernardeli/ee52749c31f95a2bc723, if I totally ditch `stateTracker`, my request counter will only reach zero after loading the mapping js and its own internal XHR requests.

Here is the output:

```
# Counter on response: 2, state is: loading
# URL: http://red-hat-overpass-fonts.s3.amazonaws.com/overpass_regular-webfont.woff
# Counter on response: 1, state is: loading
# URL: http://red-hat-overpass-fonts.s3.amazonaws.com/overpass_bold-webfont.woff
# Counter on request: 2, state is: loading
# URL: http://open.mapquestapi.com/geocoding/v1/address?key=Fmjtd%7Cluurn96z2l%2Cr2%3Do5-9w8agr&outFormat=json&location=Brisbane%2C%20Australia
# Counter on response: 1, state is: loading
# URL: http://redhatbrand.github.io/SalesKickOffTemplates/shared/javascripts/vendor/d3.v3.min.js
# Counter on request: 2, state is: loading
# URL: http://tile.openstreetmap.us/vectiles-water-areas/12/3788/2372.topojson
# Counter on request: 3, state is: loading
# URL: http://tile.openstreetmap.us/vectiles-water-areas/12/3789/2372.topojson
# Counter on request: 4, state is: loading
```

I know that by removing `stateTracker`, I won't get a bunch of things like state changing, breaking pretty much everything.... So I got rid of the following lines inside stateTracker: https://github.com/kapouer/node-webkitgtk/blob/master/webkitgtk.js#L1026-L1058

I have now ALL urls that I expect to load (the ones with tile.openstreetmap.us)

```
# URL: http://open.mapquestapi.com/geocoding/v1/address?key=Fmjtd%7Cluurn96z2l%2Cr2%3Do5-9w8agr&outFormat=json&location=Brisbane%2C%20Australia
# Counter on response: 1, state is: loading
# URL: http://redhatbrand.github.io/SalesKickOffTemplates/shared/javascripts/vendor/moment.js
loopAgain: 0
# Counter on request: 2, state is: idling
# URL: http://tile.openstreetmap.us/vectiles-water-areas/12/3788/2372.topojson
# Counter on request: 3, state is: idling
# URL: http://tile.openstreetmap.us/vectiles-water-areas/12/3789/2372.topojson
# Counter on request: 4, state is: idling
# URL: http://tile.openstreetmap.us/vectiles-water-areas/12/3788/2373.topojson
# Counter on request: 5, state is: idling
# URL: http://tile.openstreetmap.us/vectiles-water-areas/12/3789/2373.topojson
# Counter on request: 6, state is: idling
# URL: http://tile.openstreetmap.us/vectiles-water-areas/12/3788/2371.topojson
```

The state has moved to idling here, but requests counter hasn't reached zero, and all requests I expect has actually been finished after a few seconds.

Note that I removed code that must be essencial for other parts, and I can't figure out why it works without them.

Ideas?

Thanks for your help @kapouer :)

**Comment by kapouer** [comment]
You actually do not have to fiddle with the inner workings...
README says:
```To keep the gtk loop running forever, just listen to "unload" event.```
You just do not have to call `loop()` yourself (and nothing good will come out of it).
It's designed to run the gtk loop unless you're not waiting something to happen.
Also, when using the chainable API, it's better to use `.wait('unload')` instead of `.once('unload')`,
as in the example i wrote in the previous comment.

**Comment by kapouer** [comment]
That being said, i'm looking at the web page you're trying to render.
The "stall" load parameter, set to a higher value, should fix it, but it doesn't so clearly something does not work.

**Comment by bernardeli** [comment]
All the in-betweens lines are just for debugging purposes. In the end, I can see where the request is going.

Setting `stall` didn't fix, unfortunately. 

This is my latest script:

```
var Webkit = require('webkitgtk');

var url       = 'http://d3s84xo5cmutkt.cloudfront.net/renders/attachments/000/011/601/original/latest_just-map.html';
var options   = { width: 567, height: 756, stall: 100000 }; // Pixels
var filename  = 'output.pdf';
var paperSize = { paper: { width: 150, height: 200, unit: 'mm' } };

Webkit()
  .load(url, options)
  .wait('idle')
  .pdf(filename, paperSize, function(){ console.log('Rendering to pdf'); })
  .destroy();
```

Stall is fairly high here. It doesn't seem to take it in consideration.

**Comment by kapouer** [comment]
Found the problem by just looking at console in debug mode.
```
XMLHttpRequest cannot load http://tile.openstreetmap.us/vectiles-highroad/12/3790/2374.topojson. Request header field X-webkitgtk1424161649978 is not allowed by Access-Control-Allow-Headers.
```
I think i can fix this.

**Comment by bernardeli** [comment]
Would you mind sharing how you got to the error?

I tried to set `console: true` and `debug: true`, and added a listener `on('console')`.

I haven't got to the error though.

```
var Webkit = require('webkitgtk');

var url       = 'http://d3s84xo5cmutkt.cloudfront.net/renders/attachments/000/011/601/original/latest_just-map.html';
var options   = { console: true, width: 567, height: 756, debug: true }; // Pixels
var filename  = 'renders/output.pdf';
var paperSize = { paper: { width: 150, height: 200, unit: 'mm' } };

webkit = Webkit();

webkit.on('console', function(level, error){
  console.log(error);
});

webkit.load(url, options)
  .wait('idle')
  .pdf(filename, paperSize, function(){ console.log('Rendering to pdf'); })
  .destroy();
```

Would love to be able to know how you got there so next time I don't need to bother you too much like today :-)

**Comment by kapouer** [comment]
`debug: true` is an option of `WebKit()`,
`console: true` is an option of `.load().`

**Comment by kapouer** [comment]
Please update and try generating pdf again ;)

**Comment by kapouer** [comment]
I was workarounding badly against a problem i had with a race condition. Still got it, but it happens in edge (and really useless) cases, so i removed the workaround, added a test to guard it, and published a new version not messing with request headers.

**Comment by kapouer** [comment]
Oh and you really don't need to listen to "unload" event in your case.
Listening to that event is really when you want to keep a page running - not when you want a pdf output and close it.

**Comment by bernardeli** [comment]
Man, that's really great. Appreciated all your effort put into it. Thanks a million!

**Comment by bernardeli** [comment]
One more thing I just found...

This all works great when I start webkit with debug: true, but it quits unexpectedly when debug is removed. Was it desired behaviour?

**Comment by kapouer** [comment]
What do you mean by "it quits"
the flie is generated then the script ends - isn't it what you want to do ?

**Comment by kapouer** [comment]
are you familiar with nodejs ?

**Comment by bernardeli** [comment]
Yes, I am familiar with nodejs :)

Yes, it is what I want - after I call pdf(), it renders and destroys, and node process quits. That's perfect. All good here. 

The problem sits when I remove debug: true. The new workaround you've just pushed only worked for me when I initialise with Webkit({ debug: true });

Example here:

```
var Webkit = require('webkitgtk');

var url       = 'http://d3s84xo5cmutkt.cloudfront.net/renders/attachments/000/011/601/original/latest_just-map.html';
var options   = { width: 567, height: 756, console: true };
var requests  = 0;
var filename  = 'renders/output.pdf';
var paperSize = { paper: { width: 150, height: 200, unit: 'mm' } };

var webview = Webkit({ debug: true });

webview.load(url, options)
    .pdf(filename, paperSize, function() { console.log("Rendering"); })
    .destroy();

webview.on('request', function (request) {
  requests += 1;
});

webview.on('response', function (response) {
  requests -= 1;
  console.log(webview.readyState);
  if (requests === 0) print();
});


function print(){
  webview
    .pdf(filename, paperSize, function() { console.log("Rendering"); })
    .destroy();
}
```

With this very same script above, try remove `{ debug: true }`. That quits with no error raised. That's what I meant.

Note that I'm counting requests again. It turns `complete` before all requests have finished. That being said, I can't rely on `wait('idle')`.

Not positive if it is an issue there. I don't mind keep my script with `debug: true` as timing and process power isn't a problem.

**Comment by kapouer** [comment]
You have to rely on 'load' or 'idle' event. 'idle' /is counting requests for you/.
`WebKit().load(url).wait('idle').pdf(...)`
will do exactly what you want here.

**Comment by kapouer** [comment]
Give it a try... it renders the pdf all right.

**Comment by kapouer** [comment]
```
var Webkit = require('webkitgtk');
var url       = 'http://d3s84xo5cmutkt.cloudfront.net/renders/attachments/000/011/601/original/latest_just-map.html';
var options   = { width: 567, height: 756, console: true };
var requests  = 0;
var filename  = 'output.pdf';
var paperSize = { paper: { width: 150, height: 200, unit: 'mm' } };

Webkit().load(url, options).wait('idle').pdf(filename, paperSize).destroy(function(err) {
  // here catch any error that happened in any of those calls
  if (err) console.error(err);
});
```

**Comment by bernardeli** [comment]
I may have expressed myself badly. I get the file, I don't get it rendered correctly. Maps don't show up. Have you checked the file? Is yours as exactly as the [url I'm using](http://d3s84xo5cmutkt.cloudfront.net/renders/attachments/000/011/601/original/latest_just-map.html) ?

This is my output.pdf: http://cl.ly/0g2E2T12461W

Maps tiles are not loading for me at all. It must be something with my setup now.

--- 
On the requests counter topic... 

I added the following - 

```
webview.on('response', function (response) {
  requests -= 1;
  console.log("Missing responses: " + requests + ". Webview readyState: " + webview.readyState);
  if (requests === 0) print();
});
```

And the output is:

```
....
Missing responses: 2. Webview readyState: loading
Missing responses: 1. Webview readyState: loading
Missing responses: 1. Webview readyState: loading
Missing responses: 3. Webview readyState: interactive
Missing responses: 2. Webview readyState: interactive
Missing responses: 1. Webview readyState: interactive
Missing responses: 32. Webview readyState: complete
Missing responses: 31. Webview readyState: complete
Missing responses: 30. Webview readyState: complete
Missing responses: 29. Webview readyState: complete
Missing responses: 28. Webview readyState: complete
..... and goes until zero.
```

So if I rely on `wait('idle')`, the `pdf()` is called before the requests are finished. Therefore the javascript execution isn't fully finished for the case scenario. Make sense?

**Comment by bernardeli** [comment]
Anyhow, I may not be able to spot whether the wait('idle') is a bug or not... I have the outcome I was expecting with the initial issue I posted by cheating a bit with my counters as well as having debug set to true. I think it's really great that I get the pdf in a way or in the other. 

I definitely appreciate your work and all effort you've put into this project. You absolutely rock!

**Comment by kapouer** [comment]
I see all tiles when i generate the pdf - and it is nicely aligned with paper size.
The bug is fixed. Now all you see is normal behavior.
If your internet connection is slower than mine, it is perfectly possible the tiles requests stall !
Just set a higher value for `stall` parameter (in milliseconds). Mind that if you want to set a very high value, like 60000, it is meaningless if you don't also change the `timeout` value.
Correcting the previous snippet:
```
var options   = { width: 567, height: 756, console: true, stall: 300000, timeout: 300000 }; // 5 minutes
```

**Comment by kapouer** [comment]
Explanation: `idle` event takes care of tracking requests/responses, timeouts, intervals, even animation frames. But it is designed to be the fastest it can on *any* website, so it marks an xhr request as stalled and ignores it as soon as it takes longer than `stall` param to get the data, stall being very small - a production value.

**Comment by bernardeli** [comment]
I perfectly understand now. Stall was the answer. It has loaded all tales. 

Thanks once again.

**Comment by kapouer** [comment]
FYI you will like to use either
`DEBUG=webkitgtk:stall node app.js`
or
`require('debug').enable('webkitgtk:stall');`
in your application.
